version: 1
formatters:
  default:
    format: '[%(asctime)s] %(levelname)s in %(module)s: %(message)s'
    datefmt: '%Y-%m-%d %H:%M:%S'
  simple:
    format: '%(asctime)s - %(name)s - %(levelname)s - %(message)s'
    datefmt: '%Y-%m-%d %H:%M:%S'
handlers:
  console:
    class: logging.StreamHandler
    level: DEBUG
    formatter: default
    stream: ext://sys.stdout
  file:
    class: logging.handlers.RotatingFileHandler
    level: INFO
    formatter: default
    filename: logs/app.log
    maxBytes: 10485760 # 10MB
    backupCount: 5
    encoding: utf8
loggers:
  fastapi:
    level: INFO
    handlers: [console, file]
    propagate: no
  uvicorn:
    level: INFO
    handlers: [console, file]
    propagate: no
  uvicorn.access:
    level: INFO
    handlers: [console, file]
    propagate: no
root:
  level: DEBUG
  handlers: [console, file]